apiVersion: v1
kind: Service
metadata:
  name: simple-spring-service
  namespace: jenkins
spec:
  type: NodePort
  selector:
    app: simple-spring
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-spring-deployment
  labels:
    app: simple-spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-spring
  template:
    metadata:
      labels:
        app: simple-spring
    spec:
      containers:
      - name: nginx
        image: boonchu/simple-spring
        ports:
        - containerPort: 80
